### ISSUE TITLE
Create a README

### ISSUE THREAD

**Issue by hannahro15** [hannahro15/July24Hackathon-United-Events#3]

**Comment by hannahro15** [comment]
Tasks: 

 [ ]  #2 - Create Wireframes
 [ ] Add user stories to README
 [ ] Add a features section to the README
 [ ] Add credits section to the README
 [ ] Add deployment section to the README

**Comment by TravelTimN** [comment]
I actually have a magic tool I've created for my students to help with the README. Whoever is handling the README, let me know, I can provide access to this amazing tool 🤩

**Comment by hannahro15** [comment]
I am handling the readme for now.
